FROM ubuntu:jammy
SHELL ["/bin/bash", "-l", "-c"]

ARG DEBIAN_FRONTEND=noninteractive
ARG HOME=/root
RUN apt update
RUN apt install -y \
  python3-pip \
  git \
  libboost-dev \
  libboost-filesystem-dev \
  libboost-program-options-dev \
  libboost-test-dev \
  libzmq5-dev python3-dev \
  build-essential swig cmake git

RUN apt install -y nano libxtst6 libxi6 libxrender1 wget firefox

WORKDIR $HOME

# build + install HELICS
RUN git clone https://github.com/GMLC-TDC/HELICS
WORKDIR $HOME/HELICS
RUN mkdir -p build
WORKDIR $HOME/HELICS/build
RUN cmake ..
RUN make -j$(nproc)
RUN make install
RUN ldconfig
RUN echo "export LD_LIBRARY_PATH=/usr/local/lib" >> ~/.bashrc

WORKDIR $HOME

# install GridLAB-D
RUN wget https://github.com/gridlab-d/gridlab-d/releases/download/v5.1/GridLAB-D-5.1.0-Linux.deb
RUN dpkg -i GridLAB-D-5.1.0-Linux.deb

# install miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -b
ENV PATH /root/miniconda3/bin:$PATH
RUN sed -e '/[ -z "$PS1" ] && return/s/^/#/g' -i /root/.bashrc

# create conda environment & install python requirements
RUN /root/miniconda3/bin/conda init bash
COPY conda_env.yml .
RUN conda env create -f conda_env.yml
RUN echo "conda activate cosim" >> ~/.bashrc
RUN emobpy create -n unused

WORKDIR /PEMT-CoSim

ENTRYPOINT [ "conda", "run", "--no-capture-output", "-n", "cosim", "python3", "-u", "generate_case.py"]
